dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

      # User/password auth
      user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"

      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      database: 'DEV_SANDBOX'
      warehouse: 'DEV_WH'
      schema: 'RTZONEVA' 
      threads: 1
      client_session_keep_alive: False
      query_tag: github_action_query

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
