# dbt_project:
  
#   outputs:
#     dev:
#       type: snowflake
#       threads: 1
#       account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

#       # User/password auth
#       user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" 
#       password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"

#       role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
#       database: 'DEV_SANDBOX'
#       warehouse: 'DEV_WH'
#       schema: 'RTZONEVA'
#       client_session_keep_alive: False
#       query_tag: github_action_query

#       # optional
#       connect_retries: 0 # default 0
#       connect_timeout: 10 # default: 10
#       retry_on_database_errors: False # default: false
#       retry_all: False  # default: false
#       reuse_connections: False # default: false (available v1.4+)
#   target: dev

dbt_project:
  
  outputs:
    dev:
      type: snowflake
      threads: 1

      # User/password auth
      account: 'zx15293.eu-west-3' # 'ey37413.eu-west-3' or "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: RTZONEVA #"{{ env_var('DBT_SNOWFLAKE_USERNAME') }}"
      role: SYSADMIN # "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      password: 'Rtzoneva1234!' # "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      database: DEV_SANDBOX # "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
      warehouse: DEV_WH # "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      schema: RTZONEVA #"{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
      client_session_keep_alive: False
      query_tag: github_action_query

      # optional
      connect_retries: 1 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
  target: dev
