

dbt_project:
  
  outputs:
    dev:
      type: snowflake
      threads: 1

      account: https://snwflk_gtb.eu-west-1.snowflakecomputing.com/ # 'snwflk_gtb.eu-west-1'
      user: RUMIANA_TZONEVA
      password:  "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      role: ACCOUNTADMIN
      database: DEV_SANDBOX 
      warehouse: COMPUTE_WH 
      schema: RTZONEVA
  
      client_session_keep_alive: False
      query_tag: github_action_query

      # optional
      connect_retries: 2 # default 0
      connect_timeout: 20 # default: 10
      retry_on_database_errors: True # default: false
      #retry_all: False  # default: false
      #reuse_connections: False # default: false (available v1.4+)
  target: dev
