

dbt_project:
  
  outputs:
    dev:
      type: snowflake
      threads: 1
      #account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 
      # user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" 
      # password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      #role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"


      account: 'snwflk_gtb.eu-west-1'
      user: RUMIANA_TZONEVA
      password: "{{ secrets.SNOWFLAKE_PASSWORD }}"  
      role: ACCOUNTADMIN
      database: DEV_SANDBOX 
      warehouse: COMPUTE_WH 
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_TEST') }}" 
      
      # database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}" 
      # warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}" 
      # schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}" 
      threads: 1
      client_session_keep_alive: False
      query_tag: github_action_query

      # optional
      connect_retries: 2 # default 0
      connect_timeout: 20 # default: 10
      retry_on_database_errors: True # default: false
      #retry_all: False  # default: false
      #reuse_connections: False # default: false (available v1.4+)
  target: dev
