
version: 2

models:
  - name: cust_model
    description: "A starter dbt model"
    columns:
      - name: cid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "The name of the customer"
        tests:
          - not_null