name: schedule_dbt_run

on: 
    pull_request:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            DBT_PROFILES_DIR: ./

            DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
            DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW }}
            DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}

        steps:
        - name: Check out
          uses: actions/checkout@master
    
        - name: Setup Python
          uses: actions/setup-python@v4
          with: 
            python-version: "3.9"

        - name: Install dependencies
          run: |
            pip install dbt
            dbt deps

        # dbt related commands here - run use --target prod/dev to run for specific environments
        - name: Run dbt models
          run: dbt run

        - name: Test dbt models
          run: dbt test
