name: build_models

on: 
    pull_request:
        branches: ["main"]
    
    workflow_dispatch:

env:
    DBT_PROFILES_DIR: ./
    
    SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
    SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    SNOWFLAKE_ROLE: ACCOUNTADMIN
    SNOWFLAKE_DATABASE: DEV_SANDBOX
    SNOWFLAKE_WAREHOUSE: DEV_WH
    SNOWFLAKE_SCHEMA: RTZONEVA 
    
    ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
    USER: ${{ secrets.SNOWFLAKE_USERNAME }}
    PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    ROLE: ACCOUNTADMIN
    DATABASE: DEV_SANDBOX
    WAREHOUSE: DEV_WH
    SCHEMA: RTZONEVA 

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            #DBT_PROFILES_DIR: ./
            
            SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
            SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE: ACCOUNTADMIN
            SNOWFLAKE_DATABASE: DEV_SANDBOX
            SNOWFLAKE_WAREHOUSE: DEV_WH
            SNOWFLAKE_SCHEMA: RTZONEVA 
            
            ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
            USER: ${{ secrets.SNOWFLAKE_USERNAME }}
            PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            ROLE: ACCOUNTADMIN
            DATABASE: DEV_SANDBOX
            WAREHOUSE: DEV_WH
            SCHEMA: RTZONEVA 
            
            # DBT_SNOWFLAKE_DATABASE: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
            # DBT_SNOWFLAKE_WAREHOUSE: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
            # DBT_SNOWFLAKE_SCHEMA: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}" 

        steps:
        - name: Check out
          uses: actions/checkout@master
          with:
              persist-credentials: true
    
        - name: Setup Python
          uses: actions/setup-python@v4
          with: 
            python-version: "3.9"

        - name: Install dependencies
          run: |
            pip3 install dbt-snowflake
            dbt deps
         
        - name: Dump GITHUB_CONTEXT
          run: echo ${{ github.workspace }}

        - name: DBT DEBUG
          run: dbt debug --profiles-dir $PWD
        
        # dbt related commands here - run use --target prod/dev to run for specific environments
        # - name: Run dbt models
        #   run: dbt run --profiles-dir $PWD

        # - name: Test dbt models
        #   run: dbt test
